// <auto-generated />
using Hugin.Console.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hugin.Console.Data.Migrations
{
    [DbContext(typeof(HuginDbContext))]
    partial class HuginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Hugin.Console.Data.ReviewMarkRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReviewedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReviewMarks");
                });

            modelBuilder.Entity("Hugin.Core.Models.Ad", b =>
                {
                    b.Property<string>("FeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployerOrgnr")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Expires")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MunicipalityNumber")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FeedId");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Hugin.Core.Models.Company", b =>
                {
                    b.Property<string>("Orgnr")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBranch")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenInRegister")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MunicipalityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOrgnr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Orgnr");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Hugin.Core.Models.PipelineEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orgnr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SvarText")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Orgnr")
                        .IsUnique();

                    b.ToTable("Pipeline");
                });

            modelBuilder.Entity("Hugin.Core.Models.SyncState", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Source");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
