<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>hugin-api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hugin.Core\Hugin.Core.csproj" />
    <ProjectReference Include="..\Hugin.Infrastructure\Hugin.Infrastructure.csproj" />
  </ItemGroup>

</Project>
